name: only main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Unzip and remove zip files
      - name: unzip file
        run: unzip -qq './data/*.zip' -d ./data && rm ./data/*.zip

